"""set up basic tables

Revision ID: 1953ca29746c
Revises: 
Create Date: 2018-03-07 16:56:57.862666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1953ca29746c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scripts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location_information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scene_number', sa.String(length=10), nullable=True),
    sa.Column('int_or_ext', sa.String(length=8), nullable=True),
    sa.Column('location_type', sa.String(), nullable=True),
    sa.Column('time_of_day', sa.String(length=20), nullable=True),
    sa.Column('script_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('location_information')
    op.drop_table('scripts')
    # ### end Alembic commands ###
